config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users
  resources :deeds do 
    resources :funds, only: [:create, :destroy]
    resources :uninteresteds, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resources :ratings, only: [:create, :destroy]
  end 
  resource :sessions, only: [:new, :create, :destroy]


  get("/users/:id/created", { to: "users#created_deeds", as: :created_deeds})

  get("/users/:id/funded", { to: "users#funded_deeds", as: :funded_deeds})

  get("/deeds/near_me/all", { to: "deeds#near_me", as: :near_me})

  get("/deeds/fully_funded/all", { to: "deeds#fully_funded", as: :fully_funded})

  get 'tags/:tag', to: 'deeds#index', as: "tag"

  resources :complete_fundings, only: :create

  get("/about", { to: "welcome#about", as: :about})
  root({ to: 'welcome#index' })
  
end

app/models/user.rb
class User < ApplicationRecord
    has_many :deeds, dependent: :destroy    
    has_many :funds, dependent: :destroy
    has_many :funded_deeds, through: :funds, source: :deed 
    has_many :comments, dependent: :destroy
    has_secure_password 
    has_one_attached :image

    has_many :uninteresteds, dependent: :destroy
    has_many :unintereseted_deeds, through: :uninteresteds, source: :deed

    has_many :ratings, dependent: :destroy
    has_many :rated_deeds, through: :ratings, source: :deed

    geocoded_by :address
    after_validation :geocode
    reverse_geocoded_by :latitude, :longitude

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

    validates :username, presence: true, uniqueness: true
    validates :wallet, presence: true
    validates :city, presence: true

    validates :email, presence: true, 
        uniqueness: true,
        format: VALID_EMAIL_REGEX

    def full_name
        "#{first_name.capitalize} #{last_name.capitalize}".strip
    end

    def address
        [city].compact.join(', ')
    end


    extend FriendlyId
    friendly_id :full_name, use: [:slugged, :history, :finders]

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :find_current_user, only: [:edit, :update, :destroy]
  before_action :find_user, only: [:show, :created_deeds]
  #before_action :set_location


  def new
      @user = User.new
  end 

  def show 
  end 

  def edit
  end 


  def update
    if @user.update user_params
    redirect_to user_path(@user.id)
    else
    render :edit
    end
end

  def create
    @user = User.new user_params
    if @user.save
    #  session[:user_id] = @user.id
      flash[:success] = "Thank you for signing up!"
      session[:user_id] = @user.id
      redirect_to root_path
    else
  
      render :new
    end
  end

  def created_deeds
    @deeds = find_user.deeds
  end

  def funded_deeds
    @deeds = find_user.funded_deeds
  end

  private

  def user_params
    params.require(:user).permit(
      :username,                                      
      :first_name,
      :last_name,
      :location, 
      :email,
      :wallet,
      :image_url,
      :password,
      :address,
      :city,
      :longitude,
      :latitude,
      :image,
      :password_confirmation
    )
  end

  def find_current_user
    @user = current_user
  end

  def find_user
    @user = User.find params[:id]
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_deed_index.html.erb
<div class="container">
  <div class="row justify-content-md-center" id="deed-index">
    <% @deeds.each do |d| %>
      <div class="col-lg-4 col-sm-12 col-md-6" id="<%= d.id %>">
        <div class="card m-4 container-fluid p-0 card-shadow">
          <div class ="deed_container">
            <%= image_tag d.image.variant(resize: '400X400'), class: 'img-fluid' if d.image.attached?%>
          </div>
          <div class="card-header bg-primary" >
            <h5 class="card-title"><%= link_to d.title.slice(0, 50), deed_path(d) , :class=>"text-light"%></h5>
          </div>
          <div class="card-body bg-light">
            <li class="list-group-item">Raised: $<%= d.funds.count%> out of $<%= d.money_required%></li>
            <li class="list-group-item">
              <p class="card-title">
                <% if current_user.present? %>
                  <% pre_fund = d.funds.find { |fund| fund.user_id == current_user.id} %>
                  <% if pre_fund %>
                    <%= button_to 'Unfund', deed_fund_path(d, pre_fund), method: :delete %>
                  <% else %>
                    <%= button_to 'Fund', deed_funds_path(d), method: :post %>
                  <% end %>
                <% end %>
              </p>
            </li>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/created_deeds.html.erb
<div class="container">
  <% if @deeds == [] %>
    <div class="row justify-content-center">
      <p> No deeds created yet...</p>
    </div>
  <% else %>
    <%= render 'deed_index'%>
  <% end %>

app/views/users/edit.html.erb
<div class="row d-flex justify-content-center">
  <div class="col-xl-6 col-lg-9 col-md-11">
    <h1 class="mx-2">Edit</h1>
    <% if @user.errors.any? %>
      <% @user.errors.full_messages.each do |msg| %>
        <%  flash.now[:danger] = msg %>
      <% end %>
    <% end %>
    <%= simple_form_for @user do |f| %>
      <div class="form-group mx-2">
        <%= f.input :username %>
        <%= f.input :first_name%>
        <%= f.input :last_name%>
        <%= f.input :wallet%>
        <%= f.input :city%>
        <%= f.input :image %>
        <%= f.submit 'Update', ({class: "btn btn-primary"}) %>
      <% end %>
    </div>
  </div>

app/views/users/funded_deeds.html.erb
<div class="container">
  <% if @user.funded_deeds == [] %>
    <div class="row justify-content-center">
      <h2> <%=@user.username%> hasn't funded any deeds yet...</h2>
    </div>
  <% else %>
    <%= render 'deed_index'%>
  <% end %>

app/views/users/new.html.erb
<div class="row d-flex justify-content-center">
  <div class="col-xl-6 col-lg-9 col-md-11">
    <div class="card m-4 container-fluid p-0 card-shadows">
      <div class="card-header">
        <h1 class="mx-2">Sign Up</h1>
        <% if @user.present? %>
        <% end %>
      </div>
      <br>
      <div class="card-body">
        <% if @user.errors.any? %>
          <% @user.errors.full_messages.each do |msg| %>
            <%  flash.now[:danger] = msg %>
          <% end %>
        <% end %>
        <%= simple_form_for(@user) do |f| %>
          <div class="form-group mx-2 ">
            <%= f.input :username %>
            <div class="flex-input">
              <div class="name-input"> <%= f.input :first_name%> </div>
              <div class="name-input">  <%= f.input :last_name%> </div>
            </div>
            <div class="flex-input">
              <div class="name-input"> <%= f.input :wallet%> </div>
              <div class="name-input"><%= f.input :city%></div>
            </div>
            <%= f.input :email%>
            <div class="flex-input">
              <div class="name-input"> <%= f.input :password %> </div>
              <div class="name-input"> <%= f.input :password_confirmation %> </div>
            </div>
            <%= f.input :image, label: "Profile picture" %>
            <%= f.submit({class: "btn btn-primary"}) %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/users/show.html.erb
<body id="user-profile">
  <div class="jumbotron-profile">
    <div class="col-xl-6 col-lg-9 col-md-11">
      <div class="card" style="width: 35rem;" id ="jumbotron-cards">
        <div class="row">
          <div class="col-sm-8">
            <h2 class="card-title m-4"><%= @user.first_name.titleize %> <%= @user.last_name.titleize %></h2>
          </div>
          <div class="col-sm-4 ">
            <div class="pull-right mt-4 mr-4">
              <%= image_tag @user.image.variant(resize: '200X200'), :class => " img-profile  img-responsive "  if @user.image.attached?%>
            </div>
          </div>
        </div>
        <div class="card-body ">
          <hr>
          <h5 class="card-text"> Username: <%= @user.username.titleize %></h5>
          <h5 class="card-text"> Wallet: $<%= @user.wallet %></h5>
          <h5 class="card-text"> City: <%= @user.city %></h5>
          <a href="<%=funded_deeds_path%>"
        class="btn btn-primary mr-2"> Funded Deeds <span class="badge badge-light">  <%= @user.funds.count%></span></a>
          <a href="<%=created_deeds_path%>"
        class="btn btn-secondary"> Created Deeds <span class="badge badge-light"> <%= @user.deeds.count%> </span></a>
          <%= link_to('Edit Profile', edit_user_path(@user), class: "btn btn-outline-primary m-2")%>
        </div>
      </div>
    </div>
  </div>