config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users
  resources :deeds do 
    resources :funds, only: [:create, :destroy]
    resources :uninteresteds, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resources :ratings, only: [:create, :destroy]
  end 
  resource :sessions, only: [:new, :create, :destroy]


  get("/users/:id/created", { to: "users#created_deeds", as: :created_deeds})

  get("/users/:id/funded", { to: "users#funded_deeds", as: :funded_deeds})

  get("/deeds/near_me/all", { to: "deeds#near_me", as: :near_me})

  get("/deeds/fully_funded/all", { to: "deeds#fully_funded", as: :fully_funded})

  get 'tags/:tag', to: 'deeds#index', as: "tag"

  resources :complete_fundings, only: :create

  get("/about", { to: "welcome#about", as: :about})
  root({ to: 'welcome#index' })
  
end

app/models/deed.rb
class Deed < ApplicationRecord
   
    belongs_to :user 
    has_many :comments, dependent: :destroy
    has_many :funds, dependent: :destroy
    has_many :users, through: :funds
    has_many :ratings, dependent: :destroy
    has_many :users, through: :ratings
    has_many :taggings, :dependent => :destroy
    has_many :tags, through: :taggings
    has_many :uninteresteds, dependent: :destroy
    has_many :users, through: :uninterests

    has_one_attached :image
    has_one_attached :completed_image


    validates :title, presence: true, 
    uniqueness: true,
    length: { maximum: 60}
    validates :body, presence: true,
    length: { minimum: 20, maximum: 500 }
    validates :money_required, presence: true
    validates :city, presence: true
    geocoded_by :address
    after_validation :geocode
    reverse_geocoded_by :latitude, :longitude

    include AASM 
    aasm do 
        state :not_fully_funded, initial: true 
        state :fully_funded

        event :meets_required_funding do 
            transitions from: :not_fully_funded, to: :fully_funded 
        end 
    end 

    def self.viewable 
        where(assm_state: :funded)
    end 


    def funded_by?(user)
        funds.find_by_user_id(user.id).present?
    end

    def all_tags=(names)
        self.tags = names.split(",").map do |name|
            Tag.where(name: name.strip).first_or_create!
        end
    end
      
    def all_tags
        self.tags.map(&:name).join(", ")
    end

    def self.tagged_with(name)
        Tag.find_by_name!(name).deeds
    end

    def self.uniniterested_with(name)
        Uninterested.find_by_name!(name).deeds
    end

    def address
        [city].compact.join(', ')
    end

    def percent_funded
      ((BigDecimal(funds.count)/BigDecimal(money_required))*100).floor
    end

    extend FriendlyId
    friendly_id :title, use: [:slugged, :history, :finders]
end

app/controllers/deeds_controller.rb
class DeedsController < ApplicationController

    before_action :find_deed, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show, :funded]
    
    include DeedsHelper

    def index

        if params[:tag]
        @deeds = Deed.tagged_with(params[:tag])
        else
        @not_fully_funded_deeds = Deed.all.order(created_at: :desc).not_fully_funded

            if current_user.present?
            @interested_deeds = filter_uninterested_deeds(@not_fully_funded_deeds)

            @deeds = filter_deeds_user_has_funded(@interested_deeds) 
            else 
            @deeds = @not_fully_funded_deeds
            end 

        end 
      
    end

    def funded
        @deeds = Deed.viewable.order(created_at: :desc)
    end 

    def new
        @deed = Deed.new
       
    end

    def create
        @deed = Deed.new deed_params
        @deed.user = current_user
        if @deed.save
            puts "did save"
            flash[:success] = "Deed made!"
            redirect_to deed_path(@deed)
        else
            if @deed.errors
                flash.now[:danger] = @deed.errors.full_messages.join(", ")
            end
            render :new
        end
    end 

    def show
        if params[:tag]
            @deed = Deed.tagged_with(params[:tag])
        else
       
        @deed = find_deed
        @comment = Comment.new
  
        render :show  
        end 
    end 

    def edit 
    end 

    def update
        #when updating deed, we want to clear the slug so it updates too
        @deed = find_deed
        @deed.slug = nil

        #when owner of deed updates a fully funded deed, mail all funders
        if @deed.update deed_params and @deed.fully_funded?
            mail_all_deed_funders(@deed)
            redirect_to deed_path(@deed)

        elsif @deed.update deed_params
            redirect_to deed_path(@deed)
        else
          if @deed.errors.present?
            flash[:danger] = @deed.errors.full_messages.join(" • ")
          end 
          render :edit
        end
    end

    def destroy
        @deed.destroy
        redirect_to deeds_path
    end

    def near_me
        @close_deeds = Deed.near([current_user.latitude, current_user.longitude], 100).not_fully_funded

        @interested_deeds= filter_uninterested_deeds(@close_deeds)
        @deeds = filter_deeds_user_has_funded(@interested_deeds) 


        render :index
        
    end


    def fully_funded
        @deeds = Deed.fully_funded.order(created_at: :desc)
    end



    private 

    def deed_params
        params.require(:deed).permit(:deed, 
        :title, 
        :body, 
        :money_required, 
        :image_url, 
        :location, 
        :image, 
        :completed_image, 
        :completed_body,
        :uploads,
        :money_raised,
        :all_tags,
        :uninterested,
        :address,
        :city,
        :longitude,
        :latitude,)
    end

    def find_deed
        @deed = Deed.friendly.find(params[:id])
    end

    def to_param
        "#{id}-#{title}".parameterize
    end

  

end

app/helpers/deeds_helper.rb
module DeedsHelper

    def tag_links(tags)
        tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip) }.join(", ") 
    end

    def mail_all_deed_funders(deed)
        
        deed.funds.each do |fund| 
        user = fund.user 
            DeedUpdateMailer.notify_deed_funder(user,deed).deliver_now
        end  
    end 

    def filter_deeds_user_has_funded(arr) 

        funded_deeds = [] 
        current_user.funded_deeds.each do |deed| 
            funded_deeds << deed.id
            puts deed
        end   


        @non_funded_deeds = [] 
        arr.each do |deed|
            if !funded_deeds.include? deed.id
                @non_funded_deeds << deed
            end 
        end 
        @non_funded_deeds
    end 

    def filter_uninterested_deeds(arr)
        
        uninterested_deeds = [] 
        current_user.uninteresteds.each do |deed| 
            uninterested_deeds << deed.deed_id
        end   

        @interested_deeds = []
        arr.each do |deed|
            if !uninterested_deeds.include? deed.id
                @interested_deeds << deed
            end 
        end 
        @interested_deeds
    end 


end

app/views/deeds/_completed_deed_form.html.erb
<div class="row d-flex justify-content-center">
  <div class="col-xl-6 col-lg-9 col-md-11">

    <%= simple_form_for(@deed) do |f| %>
        <div class="form-group mx-2">
        <%= f.input :title  %>
        <%= f.input :body, rows: 10, label: "Deed details" %>
        <%= f.input :money_required, label: "Money needed" %>  
        <%= f.input :city, label: "City/Town" %>
        <%= f.input :all_tags %>
        <%= f.input :image %>
        <%= f.submit({class: "btn btn-primary"}) %>
        </div>
    <% end %>

    <% if @deed.persisted? %>
          <div class="ml-auto">
            <%= link_to('Delete', deed_path(@deed), method: :delete, class: " m-2 btn btn-info", data: {confirm: "Are you sure?"}) %>
          </div>
    <% end %>
  </div>

</div>

app/views/deeds/_deed_form.html.erb
<div class="row d-flex justify-content-center">
  <div class="col-xl-6 col-lg-9 col-md-11">
    <div class="card m-4 container-fluid p-0 card-shadows">
      <div class="card-header">
        <h2 class="mx-2">Deed Deets</h2>
      </div>
      <div class="card-body">
        <% if @deed.fully_funded? %>
          <%= simple_form_for(@deed) do |f| %>
            <div class="form-group mx-2">
              <%= f.input :completed_body, rows: 10, label: "Update details" %>
              <%= f.input :completed_image, label: "Image" %>
              <%= f.submit({class: "btn btn-primary"}) %>
            </div>
          <% end %>
        <%  else  %>
          <%= simple_form_for(@deed) do |f| %>
            <div class="form-group mx-2">
              <%= f.input :title  %>
              <%= f.input :body, rows: 10, label: "Deed details" %>
              <%= f.input :money_required, label: "Money needed" %>
              <%= f.input :city, label: "City/Town" %>
              <%= f.input :all_tags %>
              <%= f.input :image %>
              <%= f.submit({class: "btn btn-primary"}) %>
            </div>
          <% end %>
          <% if @deed.persisted? %>
            <div class="ml-auto">
              <%= link_to('Delete', deed_path(@deed), method: :delete, class: " m-2 btn btn-info", data: {confirm: "Are you sure?"}) %>
            </div>
          <% end %>
        <%  end %>
      </div>
    </div>

app/views/deeds/_deed_index.html.erb
<body id="deed-index">
  <div class="container">
    <div class="row justify-content-md-center">
      <% @deeds.each do |d| %>
        <div class="col-lg-4 col-sm-12 col-md-6" id="<%= d.id %>">
          <div class="card m-3 container-fluid p-0 shadow p-3 mb-5 bg-white rounded">
            <div class ="deed_container">
              <%= image_tag d.image.variant(resize: '400X400'), class: 'img-fluid' if d.image.attached?%>
            </div>
            <div class="card-header bg-primary" >
              <h5 class="card-title"><%= link_to d.title.slice(0, 50), deed_path(d) , :class=>"text-light"%></h5>
            </div>
            <div class="card-body bg-light">
              <li class="list-group-item">Raised: $<%= d.funds.count%> out of $<%= d.money_required%>
                <div class="progress">
                  <div class="progress-bar" role="progressbar" style="width: <%= d.percent_funded%>%; " aria-valuenow="<%= d.percent_funded%>" aria-valuemin="0" aria-valuemax="100"><%= d.percent_funded%>%</div>
                </div>
              </li>
              <% if current_user.present? && d.fully_funded? === false %>
                <% pre_fund = d.funds.find { |fund| fund.user_id == current_user.id} %>
                <li class="list-group-item">
                  <p class="card-title">
                    <div id="deed-buttons-container">
                      <% if pre_fund %>
                        <%= button_to 'Unfund', deed_fund_path(d, pre_fund), method: :delete %>
                      <% else %>
                        <div>
                          <%= button_to deed_uninteresteds_path(d), method: :post do %>
                            <i class=" btn fas fa-times-circle fa-2x index-button-icon  p-0 " ></i>
                          <% end %>
                        </div>
                        <div>
                          <%= button_to deed_path(d), method: :get do %>
                            <i class=" btn fas fa-info-circle fa-2x index-button-icon-info  p-0 " ></i>
                          <% end %>
                        </div>
                        <div>
                          <%= button_to deed_funds_path(d), method: :post do %>
                            <i class=" btn fab fa-gratipay fa-2x index-button-icon p-0 "></i>
                          <% end %>
                        </div>
                      </div>
                    <% end %>
                  <% end %>
                </p>
              </li>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/deeds/edit.html.erb
<%= render 'deed_form'%>

app/views/deeds/fully_funded.html.erb
<h1 class="mx-2 text-center page-header"> Fully Funded Deeds</h1>
<hr>
<%= render 'deed_index'%>

app/views/deeds/index.html.erb
<h1 class="mx-2 text-center"> </h1>

<%= render 'deed_index'%>

app/views/deeds/near_me.html.erb
<h1 class="mx-2 text-center page-header"> Nearby Deeds</h1>
<hr>
<%= render 'deed_index'%>

app/views/deeds/new.html.erb
<%= render "deed_form"%>

app/views/deeds/show.html.erb
<div class="container">
  <div class="row">
    <%-# deed IMAGE -%>
    <div class="col">
      <div class="card mt-4 ">
        <div class="card-body ">
          <%= image_tag @deed.image,:class => "card-img-top" if @deed.image.attached?%>
        </div>
      </div>
    </div>
    <%-# deed DETAILS -%>
    <div class="col">
      <div class="card mt-4">
        <div class="card-body ">
          <h4 class="card-title"><%= @deed.title %></h4>
          <p class="card-text"><%= @deed.body %></p>
          <p class="card-text"><small class="text-muted"> Created <%= time_ago_in_words ( @deed.created_at) %> ago, by <%= link_to @deed.user.username, user_path(@deed.user.id)%> in <%= @deed.city %> </small></p>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">  Raised $<%= @deed.funds.count%> of $<%= @deed.money_required%>
              <div class="progress">
                <div class="progress-bar" role="progressbar" style="width: <%= @deed.percent_funded%>%; " aria-valuenow="<%= @deed.percent_funded%>" aria-valuemin="0" aria-valuemax="100"><%= @deed.percent_funded%>%
                </div>
              </div>
            </li>
            <li class="list-group-item">Tags: <%=raw tag_links(@deed.all_tags)%> </li>
          </ul>
          <div class="row justify-content-center m-2">
            <% pre_fund = @deed.funds.find { |fund| fund.user_id == current_user.id} %>
            <% if pre_fund && @deed.fully_funded? === false %>
              <%= button_to 'Unfund', deed_fund_path(@deed, pre_fund), method: :delete, class: "m-2 btn btn-secondary btn-lg " %>
            <% else %>
              <div id="deed-buttons-container">
                <div>
                  <%= button_to deed_funds_path(@deed), method: :post do %>
                    <i class=" btn fab fa-gratipay fa-4x index-button-icon p-0 "></i>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
          <div class="row justify-content-center">
            <div class="d-flex flex-row-reverse center-block">
              <% if can? :crud, @deed %>
                <%= link_to('Delete', deed_path(@deed), method: :delete, class: " m-2 btn btn-secondary", data: {confirm: "Are you sure?"}) %>
                <%= link_to('Edit',  edit_deed_path(@deed), class: " m-2 btn btn-info") %>
              <%end%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row mt-4">
    <div class="col ">
      <%-# If the deed is fully funded, then allow the user to update with results-%>
      <% if @deed.fully_funded? and can? :crud, @deed %>
        <li class="list-group-item align-items-center">
          <%= link_to('Give Update',  edit_deed_path(@deed), class: " m-2 btn btn-info align-items-center " ) %>
          <li class="list-group-item">
            <p class="card-body"> <%= @deed.completed_body %>  </p>
            <div class="card-body">
              <%= image_tag @deed.completed_image.variant(resize: '500X500') if @deed.completed_image.attached?%>
            </div>
          </li>
          <%-# Else if the deed is fully funded, then allow others to review-%>
        <% elsif @deed.fully_funded? and @deed.completed_body?%>
          <li class="list-group-item align-items-center">
            <h5 class="card-title"> Completed Deed: </h5>
            <p class="card-body"> <%= @deed.completed_body %>  </p>
            <div class="card-body">
              <%= image_tag @deed.completed_image.variant(resize: '500X500') if @deed.completed_image.attached?%>
            </div>
            <h4> Reviews</h4>
            <%= simple_form_for [@deed, @deed.ratings.build] do |f| %>
              <%= f.input :body,label: 'Your feedback' %>
              <%= f.input :score, label: 'Rating', collection: 1..5  %>
              <%= f.submit({class: "btn btn-primary"}) %>
            <% end %>
            <br>
            <% @deed.ratings.each do |rating| %>
              <% if rating.body? === true%>
                <div class="dialogbox">
                  <div class="body">
                    <small>
                      <%= rating.user.username unless rating.user.blank? %>
                      <%= time_ago_in_words(rating.created_at) unless rating.created_at.blank? %> ago. 
                      Rated: <%= rating.score %> / 5 stars
                    </small>
                    <span class="tip tip-left"></span>
                    <div class="message">
                      <span> <%= rating.body %></span>
                    </div>
                    <% if can? :delete, rating %>
                      <small> <%= link_to 'Delete', [@deed, rating],
                          method: :delete, data: { confirm: 'Are you sure?' } %>
                      </small>
                    <% end %>
                  </div>
                </div>
              <% end %>
            <% end %>
          <% end %>
          <%-# If the deed is fully funded, then allow others to review-%>
        </div>
      </div>
      <div class="row ">
        <%-# COMMENT - Allow others to comment on Project - if complete or not-%>
        <div class="card m-3" style="width: 100%;" >
          <div class="card-body">
            <%= simple_form_for [@deed, @deed.comments.build] do |f| %>
              <%= f.input :body, label: 'Comments' %>
              <%= f.submit({class: "btn btn-primary"}) %>
            <% end %>
            <br>
            <% if @deed.comments.count > 0 %>
              <% @deed.comments.each do |comment| %>
                <% if comment.body? === true%>
                  <div class="dialogbox">
                    <div class="body">
                      <small>
                        <%= comment.user.username unless comment.user.blank? %>
                        <%= time_ago_in_words(comment.created_at) unless comment.created_at.blank?  %>
                      </small>
                      <span class="tip tip-left"></span>
                      <div class="message">
                        <span> <%= comment.body %></span>
                      </div>
                      <% if can? :delete, comment %>
                        <small> <%= link_to 'Delete', [@deed, comment],
                          method: :delete, data: { confirm: 'Are you sure?' } %>
                        </small>
                      <% end %>
                    </div>
                  </div>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>