config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users
  resources :deeds do 
    resources :funds, only: [:create, :destroy]
    resources :uninteresteds, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resources :ratings, only: [:create, :destroy]
  end 
  resource :sessions, only: [:new, :create, :destroy]


  get("/users/:id/created", { to: "users#created_deeds", as: :created_deeds})

  get("/users/:id/funded", { to: "users#funded_deeds", as: :funded_deeds})

  get("/deeds/near_me/all", { to: "deeds#near_me", as: :near_me})

  get("/deeds/fully_funded/all", { to: "deeds#fully_funded", as: :fully_funded})

  get 'tags/:tag', to: 'deeds#index', as: "tag"

  resources :complete_fundings, only: :create

  get("/about", { to: "welcome#about", as: :about})
  root({ to: 'welcome#index' })
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmallChange</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cabin" rel="stylesheet">
    <%= favicon_link_tag asset_path('small_change_icon.jpg') %>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg bg-primary">
        <%= link_to("Small Change ", root_path, class: "nav-link small-change-icon") %>
        <div class="collapse navbar-collapse" id="navbarContent">
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <%= link_to("Find Deeds", deeds_path, class: "nav-link dropdown-toggle",id: "navbarDropdown", data: {toggle: "dropdown"}, role: "button", aria:{haspopup: "true", expanded: "false"} )%>
              <div class=" dropdown">
                <div class="dropdown-menu bg-light">
                  <%= link_to("All Deeds", deeds_path, class: "dropdown-item")%>
                  <% if user_signed_in? %>
                    <%= link_to("Near Me", near_me_path, class: "dropdown-item")%>
                    <%= link_to("Fully Funded Deeds", fully_funded_path, class: "dropdown-item")%>
                  <% end %>
                </div>
              </div>
            </li>
            <li class="nav-item">
              <%= link_to("Create Deed ", new_deed_path, class: "nav-link") %>            </li>
            <li class="nav-item">
              <%= link_to("How it works ", about_path, class: "nav-link") %>            </li>
          </ul>
          <% if user_signed_in? %>
            <div class="navbar-nav ml-auto d-flex">
              <%= link_to("Hi #{current_user.username.titleize} | Wallet: $#{current_user.wallet}  ", user_path(current_user), class: "nav-link") %>
              <%= link_to("Log out", sessions_path, method: :delete, class: "nav-link")%>
            </div>
          <% else %>
            <div class="navbar-nav ml-auto d-flex">
              <%= link_to("Log In", new_sessions_path, class: "nav-link")%>
              <%= link_to("Sign Up", new_user_path, class: "nav-link")%>
            </div>
          <% end %>
        </div>
      </nav>
    </header>
    <% flash.each do |type, message| %>
      <div class="alert alert-<%= type %> alert-dismissible fade show" role="alert">
        <%= message %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>